#!/bin/sh

set -eu

# This is a quick script to view .mps files

# Running "view-mps file.mps..." creates a file out.pdf (using rubber -d)
# and then open it with evince.
# This can be customized by editing the last two lines.

printf '\\documentclass{article}
\usepackage{graphicx}
\\begin{document}
\\begin{center}
' > out

for f in "$@"; do
printf '
\\verb+%s+ \\\\
\\hrulefill \\\\
\\includegraphics{%s} \\\\
\\hrulefill \\\\
\\vspace{2cm}
' "$f" "$f" >> out
done

printf '
\\end{center}
\\end{document}' >> out

rubber -d out
xdg-open out.pdf
